build: Update travis and linter configuration to the new standard
Update build and lint configurations to the common form, configure
matrix CI builds.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,30 +1,100 @@
-dist: xenial
-sudo: true
 language: python
+dist: focal
 
-python:
-  - "3.6"
-  - "3.7"
+stages:
+  - lint
+  - unittest
 
-addons:
-  apt:
-    packages:
-      - libsnappy-dev
-
-install:
-  - pip install flake8 pylint pytest pytest-cov yapf
-  - pip install -r requirements.txt
-
-before_script:
-  - wget https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb
-  - wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
+inc_before_install: &inc_before_install
+  # Setup the MySQL repositories
+  - wget -c 'https://repo.mysql.com/mysql-apt-config_0.8.13-1_all.deb'
+  - echo "mysql-apt-config mysql-apt-config/select-server select $MYSQL_VERSION" | sudo debconf-set-selections
+  - echo "mysql-apt-config mysql-apt-config/select-tools select Enabled" | sudo debconf-set-selections
+  - echo "mysql-apt-config mysql-apt-config/select-product select Ok" | sudo debconf-set-selections
+  - echo "mysql-apt-config mysql-apt-config/tools-component string mysql-tools" | sudo debconf-set-selections
   - sudo dpkg -i mysql-apt-config_0.8.13-1_all.deb
+  # Percona tools
+  - wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
   - sudo dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
   - sudo percona-release enable-only tools
-  - sudo apt-get update -q
-  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
-  - sudo apt-get install percona-xtrabackup-80
+  - sudo apt update
 
-script:
-  - make test
 
+inc_install: &inc_install
+  # Build Deps
+  - sudo apt install -y libsnappy-dev
+  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server percona-xtrabackup-80
+  - mysqld --version
+  # Setup common python dependencies
+  - pip install -r requirements.txt
+  - pip install -r requirements.dev.txt
+  - pip install -e .
+
+inc_unittest: &inc_unittest
+  - make unittest
+
+jobs:
+  allow_failures:
+    - stage: lint
+      python: 3.6
+      env: [MYSQL_VERSION=mysql-8.0]
+      name: fmt
+      before_install: *inc_before_install
+      install: *inc_install
+      script:
+        - make fmt
+        - if [ $(git diff --name-only --diff-filter=ACMR | wc -l ) != 0 ]; then
+          echo "Reformatting failed! Please run make fmt on your commits and resubmit!" 1>&2 ;
+          git diff ;
+          exit 1 ;
+          fi
+
+    - stage: lint
+      python: 3.6
+      env: [MYSQL_VERSION=mysql-8.0]
+      name: fmt
+      before_install: *inc_before_install
+      install: *inc_install
+      script:
+        - make typecheck
+  include:
+    - stage: lint
+      python: 3.6
+      env: [MYSQL_VERSION=mysql-8.0]
+      name: copyright
+      before_install: *inc_before_install
+      install: *inc_install
+      script:
+        - make copyright
+
+    # Run linters with our "primary" Python version.
+    - stage: lint
+      python: 3.6
+      env: [MYSQL_VERSION=mysql-8.0]
+      name: lint
+      before_install: *inc_before_install
+      install: *inc_install
+      script:
+        - make lint
+
+    # Matrix build unittests
+    - env: [MYSQL_VERSION=mysql-8.0]
+      python: '3.6'
+      stage: unittest
+      before_install: *inc_before_install
+      install: *inc_install
+      script: *inc_unittest
+
+    - env: [MYSQL_VERSION=mysql-8.0]
+      python: '3.7'
+      stage: unittest
+      before_install: *inc_before_install
+      install: *inc_install
+      script: *inc_unittest
+
+    - env: [MYSQL_VERSION=mysql-8.0]
+      python: '3.8'
+      stage: unittest
+      before_install: *inc_before_install
+      install: *inc_install
+      script: *inc_unittest
