dev: linting steps

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -162,6 +162,26 @@ jobs:
       - id: install-ubuntu
         run: make MYSQL_VERSION=${{ matrix.mysql-version }} PYTHON_VERSION=${{matrix.python-version}} PERCONA_VERSION=${{matrix.percona-version}} install-ubuntu
 
+      - id: fmt
+        continue-on-error: true
+        run: |
+          make fmt
+          if [ $(git diff --name-only --diff-filter=ACMR | wc -l ) != 0 ]; then
+          echo "Reformatting failed! Please run make fmt on your commits and resubmit!" 1>&2 ;
+          git diff ;
+          exit 1 ;
+          fi
+
+      - id: typecheck
+        continue-on-error: true
+        run: make typecheck
+
+      - id: copyright
+        run: make copyright
+
+      - id: lint
+        run: make lint
+
       - id: unittest
         run: |
           sudo -u testme make PYTHON=python${{matrix.python-version}} coverage
